#
# Replace all occurrences of 'homekube.org' with your domain.tld
# Replace all occurrences of 'homekube' with your domain
#
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-acme-secrets

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homekube-certificate-staging
  namespace: cert-manager-acme-secrets
spec:
  dnsNames:
    - '*.${HOMEKUBE_HOME}'
  secretName: homekube-tls-staging
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: admin@homekube.org
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Store LetsEncrypt private identification keys here. Read more ...
      # https://github.com/openshift/release/pull/9372
      name: cert-issuer-account-key
    solvers:
      - dns01:
          # this is important for the verification self-check
          cnameStrategy: Follow
          acmeDNS:
            host: https://auth.acme-dns.io
            accountSecretRef:
              name: acme-dns-homekube
              key: acme-dns.json
        selector:
          dnsZones:
            - '${HOMEKUBE_HOME}'
