config:
  linux.kernel_modules: ip_tables,ip6_tables,nf_nat,overlay,br_netfilter
  raw.lxc: |
    lxc.apparmor.profile=unconfined
    lxc.mount.auto=proc:rw sys:rw cgroup:rw
    lxc.cgroup.devices.allow=a
    lxc.cap.drop=
  security.privileged: "true"
  security.nesting: "true"
description: LXD profile for Kubernetes for useage with separate network profile
devices:
  root:
    path: /
    pool: default
    type: disk
name: k8s
used_by: []
