# see https://blog.simos.info/how-to-make-your-lxd-container-get-ip-addresses-from-your-lan/
config: {}
description: ""
devices:
  eth0:
    nictype: macvlan
    parent: eth0
    type: nic
name: net-macvlan
used_by: []
