## Configure oauth2 authentication
assertNoLeakedSecrets: false
grafana.ini:
  auth:
    disable_login_form: true
  auth.generic_oauth:
    enabled: true
    name: Keycloak-OAuth
    allow_sign_up: true
    client_id: homekube-dashboard
    client_secret: Lyzym6uI7dUYjyeKf40syWPnBH9IIOCI
    scopes: openid email profile offline_access roles
    email_attribute_path: email
    login_attribute_path: email
    name_attribute_path: email
    auth_url: https://auth.oops.de/realms/homekube/protocol/openid-connect/auth
    token_url: https://auth.oops.de/realms/homekube/protocol/openid-connect/token
    api_url: https://auth.oops.de/realms/homekube/protocol/openid-connect/userinfo
    role_attribute_path: contains(roles[*], 'admin') && 'Admin' || contains(roles[*], 'editor') && 'Editor' || 'Viewer'
