
---
# Copied/Modified from
# https://github.com/helm/charts/tree/master/stable/grafana#sidecar-for-datasources
apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasource-prometheus
  namespace: grafana
  labels:
    grafana_datasource: "1"
type: Opaque
stringData:
  datasource.yaml: |-
    # config file version
    apiVersion: 1

    # list of datasources that should be deleted from the database
    deleteDatasources:
      - name: Prometheus
        orgId: 1

    # list of datasources to insert/update depending
    # whats available in the database
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus-server.prometheus
      isDefault: true
      version: 1
      editable: true

