apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: ingress-grafana
  namespace: grafana
spec:
  rules:
    - host: grafana.homekube.org
      http:
        paths:
          - backend:
              serviceName: grafana
              servicePort: 80
            path: /
