apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: ingress-whoami
  namespace: whoami
spec:
  rules:
    - host: whoami.homekube.org
      http:
        paths:
          - backend:
              serviceName: whoami
              servicePort: 80
            path: /
